apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: <ECR_REPOSITORY_URI>:<IMAGE_TAG> # Jenkins will replace this
        ports:
        - containerPort: 3000
